import React, { useEffect } from "react";
import { Button } from "@mui/material";
import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";

const posCheckout: NextPage = () => {
  // 1. frontend:
  // criar um useEffect que verifica o sessionId
  // pega o client_reference_id que contém o userId
  // a partir de uma requisição do sessionId
  // REQUEST EXEMPLO: curl https://api.stripe.com/v1/checkout/sessions/cs_test_a15HZMxTo1aSsDhwKvKku7Kzi2pjRFYJ4D5goKB7Y3Kv0SwyJfWQMnJj1d -u sk_test_51HqiHpFm7x7XSTxAXGegtstsdrB3MJKlfwrfxGdZN8AfLJTdSm5QyHqbOQr3IO40uPenLpNG70LrCeNsynXNh0b500Chtup5xE:

  // 2. frontend:
  // faz uma requisição para o backend com o userId e informações do sessionId

  // 3. backend:
  // com o userId e as informações do sessionId ativa o usuário

  // 4. frontend:
  // mostra a página abaixo

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Compra Finalizada</h1>

        <p className={styles.description}>
          Parabéns! Agora é hora de aprender a programar!
        </p>

        <Button variant="contained">Caminhos</Button>
      </main>
    </div>
  );
};

export default posCheckout;
